version: "3"

services:
  activiti-service:
    container_name: 'activiti-service'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql
    container_name: 'mysql-db'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: activiti



